compressionLevel: 0

nodeLinker: node-modules

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: "@yarnpkg/plugin-version"

yarnPath: .yarn/releases/yarn-3.2.0.cjs

# https://github.com/yarnpkg/berry/issues/4014
changesetBaseRefs: ["HEAD"]
