name: Documentation Generator
on:
  push:
    branches:
      - "*"
      - "!docs"
    tags:
      - "*"
jobs:
  docs:
    name: Documentation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install

      - name: Checkout docs branch
        uses: actions/checkout@v3
        with:
          ref: "docs"
          path: "docs"

      - name: Generate documentation
        run: npm run docs

      - name: Change generated docs file name
        run: mv docs/docs.json docs/${{ github.ref_name }}.json

      - name: Commit and push
        run: |
          cd docs
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add .
          git commit -m "Docs build for ${{ github.ref_type }} ${{ github.ref_name }}: ${{ github.sha }}"
          git push
