name: Documentation Generator
on:
  push:
    branches:
      - "*"
      - "!docs"
    tags:
      - "*"
jobs:
  docs:
    name: Documentation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"
          cache-dependency-path: pnpm-lock.yaml

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Checkout docs branch
        uses: actions/checkout@v4
        with:
          ref: "distubejs/distubejs.github.io"
          path: "docs"
          token: ${{ secrets.DISTUBE_TOKEN }}

      - name: Delete old docs
        run: rm -rf docs

      - name: Generate documentation
        run: pnpm run docs

      - name: Commit and push
        run: |
          cd docs
          git config --local user.email github-actions@github.com
          git config --local user.name github-actions
          git add .
          git commit -m "Docs build for ${{ github.ref_type }} ${{ github.ref_name }}: ${{ github.sha }}"
          git push
