name: Publish DisTube Beta
on:
  release:
    types: [created]
jobs:
  publish:
    name: Build & Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - name: Install dependencies
        run: npm install

      - name: Build the package
        run: npm run build

      - name: Publish
        run: npm run publish:beta
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
