name: Publish distube@dev
on:
  release:
    types: [created]
jobs:
  publish:
    name: Build & Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "yarn"
          cache-dependency-path: yarn.lock

      - name: Install dependencies
        run: yarn --immutable

      - name: Build the package
        run: yarn build

      - name: Change version to ${{ github.event.release.tag_name }}
        run: yarn version ${{ github.event.release.tag_name }}

      - name: Publish
        run: yarn npm publish --tag dev
        env:
          YARN_NPM_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
