name: Test
on: [push, pull_request]
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "yarn"
          cache-dependency-path: yarn.lock

      - name: Install dependencies
        run: yarn --immutable

      - name: Linting
        run: yarn lint

      - name: Run TypeScript compiler
        run: yarn build:check

      - name: Run tests
        run: yarn test

      - name: Upload Coverage
        uses: codecov/codecov-action@v2
