name: Wiki
on:
  push:
    branches: [main]
    paths:
      - wiki/**
      - .github/workflows/wiki.yml
permissions:
  contents: write
jobs:
  wiki:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: Andrew-Chen-Wang/github-wiki-action@v4
